name: Code Glue
version: "1.0.0"
slug: code_glue
description: Built-in IDE to write automations and create entities in TypeScript
image: ghcr.io/digital-alchemy-ts/code-glue
arch:
  - aarch64
  - amd64
url: https://github.com/Digital-Alchemy-TS/code-glue
init: false
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 3789
panel_admin: true
panel_icon: mdi:application-braces
panel_title: Code Glue
ports:
  80/tcp: 3789
ports_description:
  80/tcp: Web interface
watchdog: "http://[HOST]:3789/api/v1/health"
backup_exclude:
  - "node_modules"
