name: Code Glue (Dev)
version: dev
slug: code_glue_dev
description: Write Automations and create entities in TypeScript (Development builds)
image: ghcr.io/digital-alchemy-ts/code-glue:dev
arch:
  - aarch64
  - amd64
url: https://github.com/Digital-Alchemy-TS/code-glue
init: false
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 3789
panel_admin: true
panel_icon: mdi:application-braces-outline
panel_title: Code Glue (Dev)
ports:
  80/tcp: 3790
ports_description:
  80/tcp: Web interface
watchdog: "http://[HOST]:3789/api/v1/health"
backup_exclude:
  - "node_modules"
